services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: arm64v8/rust:latest
    platform: linux/arm64/v8
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

