services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: ghcr.io/alphamercury/holo-toolchain-rust:latest
    platform: linux/arm64/v8
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

