name: Build Plugin snapshot ZIP
on:
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - run: npm install shx -g
      - run: npm install rollup -g
      - name: Install libudev-dev and libusb-dev
        run: sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      - name: Build release zip
        run: ./release.sh
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
      - name: Archive zip
        uses: actions/upload-artifact@v3
        with:
          name: controller-tools
          path: controller-tools-*.zip